### ISSUE TITLE
Cannot get it running

### ISSUE THREAD

**Issue by ralfw** [Mereep/assistant-gpt#1]
Please check out the numerous errors occurring during my attempt to start Assistant GPT. I'm running Python 3.11 on macOS.
<img width="794" alt="Bildschirmfoto 2023-07-02 um 13 20 07" src="https://github.com/Mereep/assistant-gpt/assets/132662/58b1ba7c-1b01-4196-a190-7aba439b3d3d">

- At least 2 keys in settings.yaml seem to be named incorrectly.
- And then there is the error `TypeError('`dumps_kwargs` keyword arguments are no longer supported.')`

I'm not a Python expert; I cannot really fix this.

**Comment by Mereep** [comment]
Hello,

1. Some keys in example settings were outdated. Renamed them.
2. Is a bit more tricky: `pydantic` (a library used here) has a new major release (2.0; which - I suppose from the error posted - you have installed) which changed some API methods:  [Relevant Pydantic Source](https://github.com/pydantic/pydantic/blob/61cdaea8817b7bf7421b242fefccd6e092c917ee/pydantic/main.py#L921). 
I did two things here:
- According to what I see in the `pydantic`Source, they dropped some features. As those are not strictly necessary for this project, I removed them. This might or might not work (will test 2.0 when I have some time; there are many changes in the library https://docs.pydantic.dev/2.0/migration/)
- I fixed the library to 1.X-releases in the projects requirements (which will need you to reinstall (`pip install ...`) the requirements)

Both fixes are in the latest update. Feel free to check out if those work on your machine.
